TravelBot/TravelBotWeb/TravelBotWeb.MVC/Controllers/HomeController.cs
using System.Globalization;
using System.Threading;
using System.Web.Mvc;
using System;
using TravelBotWeb.Common;
using TravelBotWeb.Services.Contracts;

namespace TravelBotWeb.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(IAppSettings appSettings) : base(appSettings)
        {
        }

        [OutputCache(Duration = int.MaxValue, VaryByParam = "lang")]
        public ActionResult Index(string lang)
        {
            logger.Info("Web page loading with language: " + lang);
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(lang);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(lang);   
            ViewBag.Lang = lang;
            return View();      
        }
    }
    
}

TravelBot/TravelBotWeb/TravelBotWeb.MVC/Controllers/JourneyController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Web.Mvc;
using System.Threading.Tasks;
using TravelBot.Common.Models;
using TravelBotWeb.Common;
using TravelBotWeb.Services.Contracts;
using TravelBotWeb.Services.Models;

namespace TravelBotWeb.Controllers
{
    public class JourneyController : BaseController
    {
        private readonly IUserService _service;
        private readonly IEmailService _emailService;
        protected readonly ICountryService _countryService;
        public JourneyController(IEmailService emailService,IUserService userService, IAppSettings appSettings, ICountryService countryService) : base(appSettings)
        {
            _service = userService;
            _emailService = emailService;
             _countryService = countryService; 
        }

        [ActionName("plan")]
        [OutputCache(Duration = int.MaxValue, VaryByParam = "lang")]
        public ActionResult JournyPlan(string lang)
        {
            logger.Info("Going to journey plan page with language: " + lang);
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(lang);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(lang);

            ViewBag.Lang = lang;
            
            ViewBag.CityList = _countryService.GetCountryList(lang);
            return View();
        }

        [OutputCache(Duration = int.MaxValue, VaryByParam = "lang")]
        public ActionResult TripManager(string lang)
        {
            logger.Info("Going to trip manager page with language: " + lang);
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(lang);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(lang);

            ViewBag.Lang = lang;
            return View();
        }
        
        public ActionResult HotelList(string lang, string id)
        {
            logger.Info("User requesting to browse history with language: "+lang+" and Id: "+id);

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(lang);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(lang);

            ViewBag.Lang = lang;
            ViewBag.reqId = id;
            var userSession = _service.GetUserSession(id);
            if(userSession == null)
            {
                return View("Error");
            }
            var searchObj = _service.GetSearchObjectAndRequestPriceIfNeeded(userSession, true);

            if (searchObj.HotelSearchResponse != null)
            {
                ViewBag.sufficient = true;
                ViewBag.SessionId = id;
                ViewBag.FlexDates = _service.GenerateFlexDateOptions(searchObj.HotelSearchResponse);
            }
            else
            {
                ViewBag.sufficient = false;
                //TODO : handle emails
                //Task.Run(() => _emailService.SendEmailFromUserSession(userSession, searchObj.RequestId));
            }
            ViewBag.maxBudget = "$"+userSession.PriceTo;
            return View();
        }

        public ActionResult StopSearch(string lang, string id)
        {
            logger.Info("User requesting to stop search with language: " + lang+" and Id: "+id);
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(lang);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(lang);

            ViewBag.Lang = lang;
            ViewBag.SessionId = id;
            return View();
        }
    }
}

TravelBot/TravelBotWeb/TravelBotWeb.MVC/Views/Home/Index.cshtml
<main>
    <section class="jumbotron hero-image" 
             style="background-image: url('@ViewBag.Domain/assets/images/home/hero-image.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;"
             id="index" ng-controller="indexCtrl">
        <div class="main-content bg-overlay tb-hidden">
            <h1 class="greeting">@Resources.Strings.GreetingMessage</h1>
            <h2 class="sub-greeting">@Resources.Strings.GreetingMessageTagline</h2>
            <div class="row justify-content-sm-center plan-container">
                <div class="col-sm-auto new-trip">
                    <a href="@Url.Action("plan", "Journey", new { lang = ViewBag.Lang })" class="hero-image-btn" ng-click="planDestination()">
                        <img src="@ViewBag.Domain/assets/images/home/bag.svg" class="icons" />
                        <p class="icon-text" ng-style="noWordWrap">@Resources.Strings.StartPlan</p>
                    </a>
                </div>
                <div class="col-sm-auto booking-history" ng-show="oldUser">
                    <a target="_blank" href="@ViewBag.APP_Domain/Journey/tripmanager" class="hero-image-btn">
                        <img src="@ViewBag.Domain/assets/images/home/calendar.svg" class="icons" />
                        <p class="icon-text">@Resources.Strings.HotelsList</p>
                    </a>
                </div>
            </div>
        </div>
    </section>
</main>
@section index{
    <script src="@ViewBag.Domain/js/index-min.js"></script>
    <script>
        var upcomingTripUrl = "@ViewBag.Domain/Journey/tripmanager";        
        var datesBG = "@ViewBag.Domain/assets/images/home/date-bg.png";
    </script>
}